- name: Create jenkins repo
  shell: |
    set -e 
    curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | sudo tee /etc/yum.repos.d/jenkins.repo
    sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - git
    - java-1.8.0-openjdk-devel
    - jenkins
    - python-pip
    - libselinux-python

- name: Make sure a service is running and enabled
  systemd:
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
    - jenkins

- name: Enable service Jenkins
  service:
    name: jenkins
    enabled: yes

- name: ensure firewalld uninstalled
  yum:
    name: firewalld
    state: absent

- name: Disable SELinux
  selinux:
    state: disabled 
