- name: create a vault artifactory container
  docker_container:
    name: vault_secret_manager
    image: vault
    state: started
    env:
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:1234"
    capabilities:
      - IPC_LOCK
    ports: 
      - "1234:1234"
  register: vault_metadata

- name: Wait for vault to accept connections
  wait_for:
    host: '{{ vault_metadata["ansible_facts"]["docker_container"]["NetworkSettings"]["IPAddress"] }}'
    port: "{{ item }}"
    state: drained
    connect_timeout: 1
    timeout: 30
  register: vault_running
  until: vault_running is success
  retries: 10
  with_items:
    - 1234