---
all:
  children:
    jenkins_master:
      hosts:
        host1:
          ansible_host: 3.0.57.168
          ansible_user: ec2-user
          ansible_become: true
    kubespray:
      hosts:
        host1:
          ansible_host: localhost
          ansible_user: sirawat
          ansible_become: true
          root_dir: /root/kubespray
          ip_hosts: [
            172.16.1.21,
            1172.16.1.20
          ]