- name: create a Artifactory container
  docker_container:
    name: artifactory
    image: goodrainapps/artifactory-oss
    state: started
    env:
      MIN_MAX_OPEN_FILES: 100
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    ports: 
      - "8081:8081"