- name: Build an image and push it to a private repo
  docker_image:
    build:
      path: .
    name: nexus3_custom
    tag: 1.0.0
    source: build

- name: create a Artifactory container
  docker_container:
    name: nexus_artifactory
    image: sonatype/nexus3
    state: started
    volumes:
      - nexus-data:/nexus-data
      - nexus-config:/opt/sonatype/nexus/etc/karaf
    ports: 
      - "8081:8081"