- name: Build an nexus3 custom image
  docker_image:
    build:
      path: "{{ role_path }}/files/nexus3_custom"
    name: nexus3_custom
    tag: 1.0.0
    source: build

- name: create a nexus3 artifactory container
  docker_container:
    name: nexus3_artifactory
    image: nexus3_custom:1.0.0
    state: started
    volumes:
      - nexus-data:/nexus-data
      - nexus-config:/opt/sonatype/nexus/etc/karaf
    ports: 
      - "8081:8081"
      - "18000:18000"
      - "18001:18001"
  register: nexus3_metadata

- name: Wait for nexus3 to accept connections
  wait_for:
    host: '{{ nexus3_metadata["ansible_facts"]["docker_container"]["NetworkSettings"]["IPAddress"] }}'
    port: "{{ item }}"
    state: drained
    connect_timeout: 1
    timeout: 30
  register: nexus3_running
  until: nexus3_running is success
  retries: 10
  with_items:
    - 18000
    - 18001
    - 8081