- name: create a Artifactory container
  docker_container:
    name: artifactory
    image: docker.bintray.io/jfrog/artifactory-oss
    state: started
    env:
      MIN_MAX_OPEN_FILES: "100"
    volumes:
      - artifactory_oss_data:/var/opt/jfrog/artifactory
    ports: 
      - "8081:8081"