- name: create a Artifactory container
  docker_container:
    name: nexus_artifactory
    image: sonatype/nexus3
    state: started
    volumes:
      - nexus-data:/nexus-data
    ports: 
      - "8081:8081"
      - "8082:8082"