- name: This command will change the working directory to somedir/.
  shell:
    cmd: ls -la

- name: Build an image and push it to a private repo
  docker_image:
    build:
      path: .
    name: nexus3_custom
    tag: 1.0.0
    source: build

- name: create a Artifactory container
  docker_container:
    name: nexus_artifactory
    image: sonatype/nexus3
    state: started
    volumes:
      - nexus-data:/nexus-data
      - nexus-config:/opt/sonatype/nexus/etc/karaf
    ports: 
      - "8081:8081"
    register: nexus_metadata

- name: Wait for nexus to accept connections
  wait_for:
    host: '{{ nexus_metadata["ansible_facts"]["docker_container"]["NetworkSettings"]["IPAddress"] }}'
    port: 8081
    state: drained
    connect_timeout: 1
    timeout: 30
  register: nexus_running
  until: nexus_running is success
  retries: 10