- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python-pip
    - python3
    - python3-pip
    - telnet

- name: checkout kubespray repository
  git:
    repo: https://github.com/kubernetes-sigs/kubespray.git
    dest: "{{ root_dir }}"

- name: Copy ``inventory/sample`` as ``inventory/mycluster``
  copy:
    src: "{{ root_dir }}/inventory/sample"
    dest: "{{ root_dir }}/inventory/mycluster"
    owner: root
    group: root
    mode: preserve

- name: Install dependencies from ``requirements.txt``
  pip:
    requirements: "{{ root_dir }}/requirements.txt"

- name: This command will change the working directory to somedir/.
  debug: 
    var: ip_hosts[0]

- name: Run a command using a templated variable (always use quote filter to avoid injection)
  shell: CONFIG_FILE={{ root_dir }}/inventory/mycluster/hosts.yaml python3 {{ root_dir }}/contrib/inventory_builder/inventory.py {{ ip_hosts }}
