- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python-pip
    - python3
    - python3-pip
    - telnet

- name: Checkout Kubespray from Github
  git:
    repo: https://github.com/kubernetes-sigs/kubespray.git
    dest: "{{ root_dir }}"

- name: Verify inventory/mycluster directory status
  stat:
    path: "{{ root_dir }}/inventory/mycluster"
  register: dir
  
- name: Copy ``inventory/sample`` as ``inventory/mycluster``
  shell: cp -rfp {{ root_dir }}/inventory/sample {{ root_dir }}/inventory/mycluster
  when : dir.stat.exists is not defined or dir.stat.exists == false

- name: Install dependencies from ``requirements.txt``
  pip:
    requirements: "{{ root_dir }}/requirements.txt"

- name: Install dependencies from ``requirements.txt`` with PIP3
  pip:
    requirements: "{{ root_dir }}/requirements.txt"
    virtualenv_python: python3
    executable: pip3

- name: List all hosts IP to generate inventory hosts file
  debug: 
    var: ip_hosts

- name: Verify inventory/mycluster/hosts.yaml file status
  stat:
    path: "{{ root_dir }}/inventory/mycluster/hosts.yaml"
  register: mycluster_inventory_hosts_file

- name: Generate inventory/mycluster/hosts.yaml
  shell: CONFIG_FILE={{ root_dir }}/inventory/mycluster/hosts.yaml python3 {{ root_dir }}/contrib/inventory_builder/inventory.py {{ ip_hosts[0] }} {{ ip_hosts[1] }}
  when: mycluster_inventory_hosts_file.stat.exists is not defined or mycluster_inventory_hosts_file.stat.exists == false

- name: Install kubespray
  shell: |
        cd /root/kubespray && 
        ansible-playbook -i inventory/mycluster/hosts.yaml -u ec2-user --become --become-user=root cluster.yml

- name: Make root execute kubectl command
  shell: cp -rp /usr/local/bin/kube* /bin/.