- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python-pip
    - python3
    - python3-pip
    - telnet

- name: checkout kubespray repository
  git:
    repo: https://github.com/kubernetes-sigs/kubespray.git
    dest: "{{ root_dir }}"

- name: check mycluster folder is exist
  stat:
    path: "{{ root_dir }}/inventory/mycluster"
  register: dir
  
- name: This command will change the working directory to somedir/.
  debug: 
    var: dir.stat.exist

- name: Copy ``inventory/sample`` as ``inventory/mycluster``
  shell: cp -rfp {{ root_dir }}/inventory/sample {{ root_dir }}/inventory/mycluster
  when : dir.stat.exist is undefined

- name: Install dependencies from ``requirements.txt``
  pip:
    requirements: "{{ root_dir }}/requirements.txt"

- name: Install dependencies from ``requirements.txt`` with pip3
  pip:
    requirements: "{{ root_dir }}/requirements.txt"
    virtualenv_python: python3
    executable: pip3

- name: This command will change the working directory to somedir/.
  debug: 
    var: ip_hosts

- name: Run a command using a templated variable (always use quote filter to avoid injection)
  shell: CONFIG_FILE={{ root_dir }}/inventory/mycluster/hosts.yaml python3 {{ root_dir }}/contrib/inventory_builder/inventory.py {{ ip_hosts[0] }} {{ ip_hosts[1] }} {{ ip_hosts[2] }}
