- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python-pip
    - python3
    - python3-pip
    - telnet

- name: checkout kubespray repository
  git:
    repo: https://github.com/kubernetes-sigs/kubespray.git
    dest: /root/kubespray

- name: Copy ``inventory/sample`` as ``inventory/mycluster``
  copy:
    src: /root/kubespray/inventory/sample
    dest: /root/kubespray/inventory/mycluster
    owner: root
    group: root
    mode: preserve

- name: Install dependencies from ``requirements.txt``
  pip:
    requirements: /root/kubespray/requirements.txt

- name: This command will change the working directory to somedir/.
  shell:
    cmd: echo {{ ip_hosts[0] }}