- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python-pip
    - python3
    - python3-pip
    - telnet

- name: checkout repository
  git:
    repo: https://github.com/kubernetes-sigs/kubespray.git
    dest: /root/kubespray

