- name: Verify trident-installer directory is exist
  stat:
    path: "{{ root_dir }}/trident-installer"
  register: trident_dir

- name: Download Trident Package
  shell: |
    set -x
    cd {{ root_dir }}
    wget https://github.com/NetApp/trident/releases/download/v20.04.0/trident-installer-20.04.0.tar.gz
    tar -xf trident-installer-20.04.0.tar.gz
    cd trident-installer
    cp -rp tridentctl /bin/.
  when: trident_dir.stat.exists is not defined or trident_dir.stat.exists == false
  ignore_errors: true

- name: Verify trident pod status
  shell: kubectl get pod -n trident | grep trident
  register: trident_pod
  ignore_errors: true

- name: Trident Installation Process
  shell: tridentctl install -n trident
  ignore_errors: true
  when: trident_dir.stat.exists and trident_dir.stat.exists == true and trident_pod.rc != 0

- name: Verify trident pod status
  shell: kubectl get pod -n trident | grep trident
  register: trident_pod
  ignore_errors: true

- name: Trident pod is running
  debug:
    msg: "Trident pod is running"
  when: trident_pod.rc == 0
