- name: check mycluster folder is exist
  stat:
    path: "{{ root_dir }}/trident-installer"
  register: trident_dir

- name: This command will change the working directory to somedir/.
  debug: 
    var: trident_dir.stat.exists

- name: Download Trident 
  shell: |
    set -x
    cd {{ root_dir }}
    wget https://github.com/NetApp/trident/releases/download/v20.04.0/trident-installer-20.04.0.tar.gz
    tar -xf trident-installer-20.04.0.tar.gz
    cd trident-installer
    cp -rp tridentctl /bin/.
    tridentctl install -n trident
  when: trident_dir.stat.exists is not defined
  ignore_errors: true

- name: test
  shell: kubectl get pod -n trident | grep trident
  register: trident_pod
  ignore_errors: true

- name: Check Trident pod is running
  debug:
    msg: "Trident pod is running"
  when: trident_pod.rc == 0
