properties([pipelineTriggers([githubPush()])])
pipeline {

    environment {
        GIT_URL = 'https://github.com/fpunthira/performance_test_lab.git'
    }
    /* specify nodes for executing */
    agent any
    stages {
        stage('Checkout Source Code from SCM') {
            steps {
                checkout scm
            }
        }      
        stage("Playbook Validation") {
           steps {
               dir("ansible") {
                sh 'ls -la'
                sh 'ansible-lint playbook.yaml'
               }
           }

        }  
        stage('Run Playbook') {
           steps {
               dir("ansible") {
                sh 'ls -la'
                sh 'ansible-playbook -i inventory playbook.yaml'
               }
           }

        }
    }
 
    /* Cleanup workspace */
    post {
       always {
           deleteDir()
       }
   }
}