properties([pipelineTriggers([githubPush()])])
pipeline {

    environment {
        GIT_URL = 'https://github.com/fpunthira/performance_test_lab.git'
    }
    /* specify nodes for executing */
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }        
        stage('test') {

           steps {
               dir("ansible") {
                sh 'ls -la'
                sh 'ansible-playbook --become --become-user=root -i inventory playbook.yaml'
               }
           }

        }
    }
 
    /* Cleanup workspace */
    post {
       always {
           deleteDir()
       }
   }
}